config/routes.rb
Rails.application.routes.draw do
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: :task

  get '/tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1 class="title">To Do List</h1>

<div class="container">

  <div class="col-md-12 text-center">
    <%= link_to "Ajouter une nouvelle tâche", tasks_new_path, class: "add-button"%>
  </div>

  <div class="taskcards">
  <% @tasks.each do |task| %>
    <div class="taskcard">

      <div class="description">
        <h3><%= task.title %></h3>
        <p><%= task.details %></p>
      </div>

      <div class="update-link">
        <%= link_to "Modifier", task_edit_path(task), class: "text-decoration-none link" %>
        <%= link_to "Supprimer", task_delete_path(task), method: :delete, data: { confirm: "Are you sure?" }, class: "text-decoration-none link" %>
      </div>
    </div>
  <% end %>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to "Edit this task", task_edit_path %>
<br>
<%= @task.details %>
<br>
<%= @task.completed %>
<br>
<%= link_to "Back to list", task_path %>